version: '3'

services:
  blackjack_php:
    image: php:8.2-fpm-alpine3.17
    volumes:
      - ./app:/opt/app
    restart: always

  blackjack_nginx:
    image: nginx:1.25.2
    volumes:
      - ./app:/opt/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
    depends_on:
      - blackjack_php
    restart: always